config/routes.rb
Rails.application.routes.draw do
  #get 'todo_users/create'
  get 'todo_users/conteo', to: 'todo_users#conteo'
  #resources 'todo/:id', to: 'todo#show', as: 'show_todo'
  resources :todos, only: [:show, :index] do
    resources :todo_users, only: [:index, :create]
    post 'complete/', to:'todo_users#complete', as: 'complete_todo'  
    post 'incomplete/', to:'todo_users#incomplete', as: 'incomplete_todo'  
  end
 
  resources :todo_users, only: [:index, :create]
  
  devise_for :users
  delete 'destroy_user_session', to: 'devise/sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    has_many :todo_users
    has_many :users, through: :todo_users 
end

app/models/todo_user.rb
class TodoUser < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

after_create :set_todos
has_many :todo_users
has_many :todos, through: :todo_users

def completed_count
  self.todo_users.where(completed: true).count
end

private

  def set_todos
    @user = User.last
    @user.todos << Todo.all
    @user.save
  end

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_users_controller.rb
class TodoUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @todo_users = current_user.todo_users.where(completed: true)
  end

  def show

  end

  def create
    @todo = Todo.find(params[:todo_id])
    @todo_users = TodoUser.new(todo: @todo, user: current_user, completed: true)
    if @todo_users.save
      redirect_to todos_path, notice: 'La tarea ha sido ingresada exitosamente'
    else
      redirect_to todos_path, alert: 'La tarea no ha podido ser ingresada'
    end 
  end

  def complete
    todo = Todo.find(params[:todo_id])
    todo_user = current_user.todo_users.find_by(todo_id: todo)
    todo_user.completed = true
    todo_user.save!

    redirect_to todos_path
  end

  def incomplete
    todo = Todo.find(params[:todo_id])
    todo_user = current_user.todo_users.find_by(todo_id: todo)
    todo_user.completed = false
    todo_user.save!

    redirect_to todos_path
  end

  
  
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_todo, only: [:show]
  
  
  def index
    @todos = Todo.all
  end

  def show
    @users = User.all
    
  end




  private
  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_users
    params.requiere(:todo_users).permit(:completed)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_users_helper.rb
module TodoUsersHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExamenNToN</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%
=begin%>
 <nav class="navbar sticky-top navbar-expand-lg navbar navbar-light bg-dark">
  
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#>"> Home <span class="sr-only">(current)</span></a>
      </li>
  
      <li class="nav-item active">
        <a class="nav-link" href="#">Tareas completadas: <%= current_user.completed_count if current_user != nil %> </a>
      </li>
    </ul>
    
      <ul class="nav navbar-nav navbar-dark " >
        <% if user_signed_in? %>
          <li > <a href="#" data-method='delete'> Salir </a></li>
        <% else %>
        <li style="color:red";><a href="<%= new_user_session_path %>"> Loguearse </a></li>
        <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
        <% end %>
      </ul>
  </div>
</nav> 
<%
=end%>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#>"> Home <span class="sr-only">(current)</span></a>
      </li>
  
      <li class="nav-item active">
        <% if current_user !=nil%>
          <a class="nav-link" href="#">Tareas completadas: <%= current_user.completed_count %> </a>
        <% end %>
      </li>
    </ul>
    
      <ul class="nav navbar-nav navbar-dark " >
        <% if user_signed_in? %>
          <li > <a href="#" data-method='delete'> Salir </a></li>
        <% else %>
        <li style="color:red";> <a href="<%= new_user_session_path %>"> Iniciar sesion &nbsp</a> </li>
        <li><a href="<%= new_user_registration_path %>"> Registro </a></li>
        <% end %>
      </ul>
  </div>
</nav>


  <div class = 'container'>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/todo_users/create.html.erb
<h1>TodoUsers#create</h1>
<p>Find me in app/views/todo_users/create.html.erb</p>

app/views/todo_users/index.html.erb
<table class="table">
    <% @todo_users.each do |todo_users|%>
      <tr>
        <td> <%= todo_users.todo.name %> </td>
        <td> <%= todo_users.todo.description %> </td>
        <td> <%= todo_users.todo.photo %> </td>
        <td> <%= todo_users.completed %> </td>
      </tr>
    <% end %>
      <tr>
        <td> Total: </td>
        <td> <%= @todo_users.map{|todo_users| todo_users.todo}.count %> </td>
      </tr>
</table>

app/views/todos/index.html.erb
<h1>Tareas</h1>

<% @todos.each_slice(3) do |todo| %>
<div class='row'>
    <% @todos.each do |todo| %>
        <div class='card'style="width: 18rem;"> 
        <%= image_tag todo.photo, class: 'card-img-top' %>
            <div class="card-body">
            <h5 class="card-title"><%= todo.name %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= todo.description %></h6>
            <%# if todo.complete == true %>
                <%= button_to  "Incompleted!", todo_incomplete_todo_path(todo), class: 'btn btn-warning' %>
            <%# else %>
                <%= button_to  "Completed!", todo_complete_todo_path(todo), class: 'btn btn-primary' %> 
            <%# end %>
            <td><%= link_to "Detalles", todo_path(todo) %></td>
            </div>
        </div>
    <% end %>
    </div>
<% end %>

app/views/todos/show.html.erb
<ul>
  <li> <%= @todo.name %> </li>
  <li> <%= @todo.description %> </li>
  <li> <%= @todo.photo %> </li>
</ul>
<br>
<br>

<h4> Usuarios que han realizado esta tarea </h4>
<br>
<% @users.each do |user|%>
    <% if TodoUser.find_by(todo_id: @todo.id, user_id: user.id).completed %>
    <br>
    <ul> 
      <li><%= user.email %></li>
    </ul>
    <% end %>
<% end %>